[project]
site_url = "https://luduvo-devhub.github.io/luduvo-scripting-docs/"
site_name = "Luduvo Scripting Docs"
site_description = "Unofficial Luduvo Scripting Docs"
site_author = "Luduvo Developer Hub & Contributors"

# copyright = "Copyright &copy; 2026 Your name"

repo_url = "https://github.com/luduvo-devhub/luduvo-scripting-docs"
repo_name = "luduvo-devhub/luduvo-scripting-docs"
edit_uri = "edit/main/docs/"

nav = [
  { "Index" = "index.md" },
  { "Contributing" = "contributing.md" },

  { "API" = [
    "api/index.md",

    "api/datatypes.md",
    "api/events.md",
    "api/game.md",
    "api/globals.md",
    "api/instances.md",
    "api/query.md",
    "api/scripts.md",
    "api/systems.md",

    # NAVGEN -- COMPONENTS
{ "Components" = [
    "api/components/index.md",

    { "Admin" = "api/components/Admin.md" },
    { "AmbientLight" = "api/components/AmbientLight.md" },
    { "Anchored" = "api/components/Anchored.md" },
    { "Attachment" = "api/components/Attachment.md" },
    { "AutoLocomotion" = "api/components/AutoLocomotion.md" },
    { "AutoRotate" = "api/components/AutoRotate.md" },
    { "BodyPart" = "api/components/BodyPart.md" },
    { "BrickColor" = "api/components/BrickColor.md" },
    { "Character" = "api/components/Character.md" },
    { "CharacterAnimation" = "api/components/CharacterAnimation.md" },
    { "CharacterAppearance" = "api/components/CharacterAppearance.md" },
    { "CharacterPhysics" = "api/components/CharacterPhysics.md" },
    { "CharacterPose" = "api/components/CharacterPose.md" },
    { "CharacterRig" = "api/components/CharacterRig.md" },
    { "Collider" = "api/components/Collider.md" },
    { "CollisionGroup" = "api/components/CollisionGroup.md" },
    { "CoreMenuAction" = "api/components/CoreMenuAction.md" },
    { "CoreMenuPage" = "api/components/CoreMenuPage.md" },
    { "CoreSettingBind" = "api/components/CoreSettingBind.md" },
    { "DisplayName" = "api/components/DisplayName.md" },
    { "Exposure" = "api/components/Exposure.md" },
    { "Health" = "api/components/Health.md" },
    { "HumanoidState" = "api/components/HumanoidState.md" },
    { "Identity" = "api/components/Identity.md" },
    { "Kinematic" = "api/components/Kinematic.md" },
    { "LensFlare" = "api/components/LensFlare.md" },
    { "Light" = "api/components/Light.md" },
    { "LightShadowOff" = "api/components/LightShadowOff.md" },
    { "LimbAttachment" = "api/components/LimbAttachment.md" },
    { "Locked" = "api/components/Locked.md" },
    { "Locomotion" = "api/components/Locomotion.md" },
    { "Mesh" = "api/components/Mesh.md" },
    { "Name" = "api/components/Name.md" },
    { "NoContactFriction" = "api/components/NoContactFriction.md" },
    { "Position" = "api/components/Position.md" },
    { "PrefabAnchor" = "api/components/PrefabAnchor.md" },
    { "PrefabInstance" = "api/components/PrefabInstance.md" },
    { "PrefabNodeId" = "api/components/PrefabNodeId.md" },
    { "RenderDisabled" = "api/components/RenderDisabled.md" },
    { "RigidBody" = "api/components/RigidBody.md" },
    { "Rotation" = "api/components/Rotation.md" },
    { "Scale" = "api/components/Scale.md" },
    { "ShadowOff" = "api/components/ShadowOff.md" },
    { "Shape" = "api/components/Shape.md" },
    { "SkyBackground" = "api/components/SkyBackground.md" },
    { "SpawnPoint" = "api/components/SpawnPoint.md" },
    { "SpotCone" = "api/components/SpotCone.md" },
    { "StableId" = "api/components/StableId.md" },
    { "Stars" = "api/components/Stars.md" },
    { "SunLight" = "api/components/SunLight.md" },
    { "SunShadows" = "api/components/SunShadows.md" },
    { "SurfaceAppearance" = "api/components/SurfaceAppearance.md" },
    { "SurfaceMaterial" = "api/components/SurfaceMaterial.md" },
    { "SwingTwistJoint" = "api/components/SwingTwistJoint.md" },
    { "Transparency" = "api/components/Transparency.md" },
    { "UIClickable" = "api/components/UIClickable.md" },
    { "UIClips" = "api/components/UIClips.md" },
    { "UICorner" = "api/components/UICorner.md" },
    { "UIDisabled" = "api/components/UIDisabled.md" },
    { "UIFrame" = "api/components/UIFrame.md" },
    { "UIHidden" = "api/components/UIHidden.md" },
    { "UIListLayout" = "api/components/UIListLayout.md" },
    { "UIOrder" = "api/components/UIOrder.md" },
    { "UIRect" = "api/components/UIRect.md" },
    { "UIRoot" = "api/components/UIRoot.md" },
    { "UIScrollingFrame" = "api/components/UIScrollingFrame.md" },
    { "UISlider" = "api/components/UISlider.md" },
    { "UISliderState" = "api/components/UISliderState.md" },
    { "UIStroke" = "api/components/UIStroke.md" },
    { "UITextInput" = "api/components/UITextInput.md" },
    { "UITextSource" = "api/components/UITextSource.md" },
    { "UITextStyle" = "api/components/UITextStyle.md" },
    { "UIToggle" = "api/components/UIToggle.md" },
    { "UIToggleOn" = "api/components/UIToggleOn.md" },
    { "Velocity" = "api/components/Velocity.md" },
    { "WorldConfig" = "api/components/WorldConfig.md" },
  ] },
  # NAVGEN -- COMPONENTS END

    # NAVGEN -- PREFABS
{ "Prefabs" = [
    "api/prefabs/index.md",

    { "Character" = "api/prefabs/character.md" },
    { "Menu" = "api/prefabs/menu.md" },
    { "Part" = "api/prefabs/part.md" },
    { "Playerspawner" = "api/prefabs/playerspawner.md" },
    { "Spawnlocation" = "api/prefabs/spawnlocation.md" },
  ] },
  # NAVGEN -- PREFABS END
  ] },

  { "Examples" = [
    "examples/index.md",

    { "Parts" = [
      "examples/parts/index.md",
      "examples/parts/spinning-part.md",
      "examples/parts/moving-platform.md",
    ] },

    { "User Input (WIP)" = [
      "examples/user-input/index.md",
    ] },
  ] },
]

# extra_css = ["stylesheets/extra.css"]
# extra_javascript = ["javascripts/extra.js"]

[project.theme]
# variant = "classic"
# custom_dir = "overrides"
# favicon = "images/favicon.png"
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

# logo = "assets/logo.png"

# [project.theme.icon]
# logo = "lucide/smile"

# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/user/repo"

# [[project.extra.social]]
# icon = "fontawesome/brands/mastodon"
# link = "https://fosstodon.org/@user"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}
pymdownx.blocks.caption = {}
