# I couldn't be bothered to make all of those component docs by hand, so this script automates them
if __name__ == "__main__":
    folder = "docs/api/components"
    text = "`Position`, `Rotation`, `Scale`, `Name`, `Velocity`, `Shape`, `BrickColor`, `Transparency`, `ShadowOff`, `SurfaceMaterial`, `Mesh`, `SurfaceAppearance`, `RenderDisabled`, `Collider`, `RigidBody`, `Anchored`, `CollisionGroup`, `Kinematic`, `Locked`, `NoContactFriction`, `SwingTwistJoint`, `SpawnPoint`, `StableId`, `PrefabInstance`, `PrefabNodeId`, `PrefabAnchor`, `Attachment`, `Character`, `CharacterPhysics`, `CharacterAnimation`, `Health`, `Locomotion`, `HumanoidState`, `AutoRotate`, `CharacterRig`, `AutoLocomotion`, `LimbAttachment`, `BodyPart`, `CharacterAppearance`, `CharacterPose`, `Identity`, `DisplayName`, `Admin`, `UIRect`, `UIOrder`, `UIHidden`, `UIFrame`, `UIStroke`, `UICorner`, `UIClips`, `UITextStyle`, `UITextSource`, `UITextInput`, `UIRoot`, `UIClickable`, `UIListLayout`, `UIScrollingFrame`, `UISlider`, `UISliderState`, `UIToggle`, `UIToggleOn`, `UIDisabled`, `CoreMenuAction`, `CoreSettingBind`, `CoreMenuPage`, `Light`, `SpotCone`, `LightShadowOff`, `SunLight`, `AmbientLight`, `SkyBackground`, `SunShadows`, `Exposure`, `Stars`, `LensFlare`, `WorldConfig`"
    text = text.split(", ")
    for word in text:
        word = word.strip("`")
        with open(f"{folder}/{word}.md", "w") as f:
            f.write(f"---\nicon: lucide/box\n---\n\n!!! note\n    This is a stub and currently a work in progress. Contribute, or come back later for updates!\n\n!!! note\n    In the alpha build of Luduvo, scriptable components and components shown/organized in the editor's properties panel are completely different, with some compoents not even being accessible via the editor's properties panel and vice versa. Tread with caution.\n\n# {word}\n\nStub\n\nCurrently, this component is only accessible to scripts via [Query Filters](docs/api/query.md#Filtering) and cannot be directly read or edited through scripts.\n\n## Properties\nThis component currently has no properties editable through queries, Instances, or any other means.")
